name: directory-listing
on: [push]

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main  # Replace 'main' with the branch where you want this workflow to run

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: ./  # Set FOLDER to root (./ indicates the root directory)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: directory-listing  # Give a name to the artifact
          path: ./  # Upload the root directory as an artifact

  deploy:
    needs: pages-directory-listing
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      # URL for the deployment, it will be automatically filled by the workflow

    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: directory-listing  # Match the artifact name from the previous step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Publish the root directory to GitHub Pages
